export const PLATFORM_PERMISSIONS = {
  dashboardRead: 'platform.dashboard.read',
  storesRead: 'platform.stores.read',
  storesWrite: 'platform.stores.write',
  storesSuspend: 'platform.stores.suspend',
  storesResume: 'platform.stores.resume',
  storesDeletePreview: 'platform.stores.delete.preview',
  storesDeleteConfirm: 'platform.stores.delete.confirm',
  storesDeleteStatus: 'platform.stores.delete.status',
  storesPurgeRetry: 'platform.stores.purge.retry',
  plansRead: 'platform.plans.read',
  plansWrite: 'platform.plans.write',
  subscriptionsRead: 'platform.subscriptions.read',
  subscriptionsWrite: 'platform.subscriptions.write',
  domainsRead: 'platform.domains.read',
  domainsWrite: 'platform.domains.write',
  analyticsRead: 'platform.analytics.read',
  auditRead: 'platform.audit.read',
  healthRead: 'platform.health.read',
  healthWrite: 'platform.health.write',
  onboardingRead: 'platform.onboarding.read',
  onboardingWrite: 'platform.onboarding.write',
  notesRead: 'platform.notes.read',
  notesWrite: 'platform.notes.write',
  notesDelete: 'platform.notes.delete',
  adminsRead: 'platform.admins.read',
  adminsWrite: 'platform.admins.write',
  rolesRead: 'platform.roles.read',
  rolesWrite: 'platform.roles.write',
  settingsRead: 'platform.settings.read',
  settingsWrite: 'platform.settings.write',
  automationRead: 'platform.automation.read',
  automationWrite: 'platform.automation.write',
  automationRun: 'platform.automation.run',
  supportRead: 'platform.support.read',
  supportWrite: 'platform.support.write',
  riskRead: 'platform.risk.read',
  riskWrite: 'platform.risk.write',
  complianceRead: 'platform.compliance.read',
  complianceWrite: 'platform.compliance.write',
  financeRead: 'platform.finance.read',
  financeWrite: 'platform.finance.write',
  paymentMethodsRead: 'platform.payment_methods.read',
  paymentMethodsWrite: 'platform.payment_methods.write',
  themeTemplatesRead: 'platform.theme_templates.read',
  themeTemplatesWrite: 'platform.theme_templates.write',
  themeTemplatesPublish: 'platform.theme_templates.publish',
  themeTemplatesArchive: 'platform.theme_templates.archive',
  qaScenariosRead: 'platform.qa.scenarios.read',
  qaScenariosWrite: 'platform.qa.scenarios.write',
  qaRunsRead: 'platform.qa.runs.read',
  qaRunsWrite: 'platform.qa.runs.write',
  qaIssuesManage: 'platform.qa.issues.manage',
} as const;

export const PLATFORM_PERMISSION_LIST = Object.values(PLATFORM_PERMISSIONS);

export type PlatformPermission = (typeof PLATFORM_PERMISSION_LIST)[number];
